server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#jsp
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
#mybatis
mybatis:
  type-aliases-package: com.baizhi.ycx.entity
  mapper-locations: classpath:com/baizhi/ycx/mapper/*DaoMapper.xml
logging:
  level:
    com.baizhi.ycx.dao: debug